# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 118c3c214adc2d9837baba40b2d9c00f0f89a0092aec9731965a1bce4d43eeaed53e647e5ec964aaf4660880d54ed15008bfbafb0fc7da19af0796157a5a5207

test:
  secret_key_base: a9075ccbfc89ba940bb47b0d40fa3c89cf8a063abbe921753dec1d058b55204de80c5a13849b17c2d56b62cd021af3f47401ee1d4c41504459b99ad050162ad5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
